- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
#    - !type:RoleTimeRequirement
#      role: JobCargoTechnician
#      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 7200 #10 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 14400 #4 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skills # Corvax-Next-Skills
        skills:
        - ShuttleControl

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
